/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddBuildingRouteImport } from './routes/add-building'
import { Route as ClientFolderRouteImport } from './routes/client-folder'
import { Route as ClientsListRouteImport } from './routes/clients-list'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PopupRouteImport } from './routes/popup'
import { Route as BrochureDemoRouteImport } from './routes/brochure/demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBuildingRoute = AddBuildingRouteImport.update({
  id: '/add-building',
  path: '/add-building',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientFolderRoute = ClientFolderRouteImport.update({
  id: '/client-folder',
  path: '/client-folder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsListRoute = ClientsListRouteImport.update({
  id: '/clients-list',
  path: '/clients-list',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PopupRoute = PopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => rootRouteImport,
} as any)
const BrochureDemoRoute = BrochureDemoRouteImport.update({
  id: '/brochure/demo',
  path: '/brochure/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-building': typeof AddBuildingRoute
  '/client-folder': typeof ClientFolderRoute
  '/clients-list': typeof ClientsListRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/popup': typeof PopupRoute
  '/brochure/demo': typeof BrochureDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-building': typeof AddBuildingRoute
  '/client-folder': typeof ClientFolderRoute
  '/clients-list': typeof ClientsListRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/popup': typeof PopupRoute
  '/brochure/demo': typeof BrochureDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-building': typeof AddBuildingRoute
  '/client-folder': typeof ClientFolderRoute
  '/clients-list': typeof ClientsListRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/popup': typeof PopupRoute
  '/brochure/demo': typeof BrochureDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-building'
    | '/client-folder'
    | '/clients-list'
    | '/home'
    | '/library'
    | '/popup'
    | '/brochure/demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-building'
    | '/client-folder'
    | '/clients-list'
    | '/home'
    | '/library'
    | '/popup'
    | '/brochure/demo'
  id:
    | '__root__'
    | '/'
    | '/add-building'
    | '/client-folder'
    | '/clients-list'
    | '/home'
    | '/library'
    | '/popup'
    | '/brochure/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBuildingRoute: typeof AddBuildingRoute
  ClientFolderRoute: typeof ClientFolderRoute
  ClientsListRoute: typeof ClientsListRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  PopupRoute: typeof PopupRoute
  BrochureDemoRoute: typeof BrochureDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-building': {
      id: '/add-building'
      path: '/add-building'
      fullPath: '/add-building'
      preLoaderRoute: typeof AddBuildingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-folder': {
      id: '/client-folder'
      path: '/client-folder'
      fullPath: '/client-folder'
      preLoaderRoute: typeof ClientFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients-list': {
      id: '/clients-list'
      path: '/clients-list'
      fullPath: '/clients-list'
      preLoaderRoute: typeof ClientsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popup': {
      id: '/popup'
      path: '/popup'
      fullPath: '/popup'
      preLoaderRoute: typeof PopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brochure/demo': {
      id: '/brochure/demo'
      path: '/brochure/demo'
      fullPath: '/brochure/demo'
      preLoaderRoute: typeof BrochureDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBuildingRoute: AddBuildingRoute,
  ClientFolderRoute: ClientFolderRoute,
  ClientsListRoute: ClientsListRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  PopupRoute: PopupRoute,
  BrochureDemoRoute: BrochureDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
